# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
"$schema": "http://json-schema.org/draft-04/schema#"
type: object
title: Transaction Schema - COMPOSE specific properties
required:
- assets
- metadata
properties:
  assets:
    type: array
    minItems: 1
    items:
      "$ref": "#/definitions/asset"
  inputs:
    type: array
    title: "Transaction inputs"
    minItems: 1
    items:
      type: "object"
      required:
      - fulfills
      properties:
        fulfills:
            type: "object"
  outputs:
    type: array
    title: "Transaction outputs"
    minItems: 2
  metadata:
    type: object
    additionalProperties: true
    required:
    - consumes
    properties:
      consumes:
        type: array
        minItems: 1
        items:
          "$ref": "#/definitions/consupmtion"
definitions:
  asset:
    additionalProperties: false
    properties:
      id:
        "$ref": "#/definitions/sha3_hexdigest"
    required:
    - id
  consumption:
    additionalProperties: false
    properties:
      id:
        "$ref": "#/definitions/sha3_hexdigest"
      amount:
        type: string
        pattern: "^[0-9]{1,20}$"
    required:
    - id
  sha3_hexdigest:
    pattern: "[0-9a-f]{64}"
    type: string