name: Integration tests
on: [push, pull_request]

jobs:
  test:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Start test run
        run: docker-compose -f docker-compose.integration.yml up test

      - name: Cleanup
        run: docker-compose -f docker-compose.integration.yml down
