name: PyTest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - abci_enabled: "ABCI enabled"
            abci: "enabled"
          - abci_disabled: "ABCI disabled"
            abci: "disabled"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build container
        run: |
          if [[ "${{ matrix.abci }}" == "enabled" ]]; then
            docker-compose -f docker-compose.yml build --no-cache --build-arg abci_status=enable planetmint
          fi
          if [[ ""${{ matrix.abci }}" == "disabled"" ]]; then
            docker-compose -f docker-compose.yml build --no-cache planetmint
          fi

      - name: Check images
        run: docker images

      - name: Save image
        run: docker save -o planetmint.tar planetmint_planetmint

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: planetmint-abci-${{matrix.abci}}
          path: planetmint.tar
          retention-days: 5


  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - db: "MongoDB with ABCI"
            host: "mongodb"
            port: 27017
            abci: "enabled"
          - db: "MongoDB without ABCI"
            host: "mongodb"
            port: 27017
            abci: "disabled"
          - db: "Tarantool with ABCI"
            host: "tarantool"
            port: 3303
            abci: "enabled"
          - db: "Tarantool without ABCI"
            host: "tarantool"
            port: 3303
            abci: "disabled"

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download planetmint
        uses: actions/download-artifact@v3
        with:
          name: planetmint-abci-${{ matrix.abci }}

      - name: Load planetmint
        run: docker load -i planetmint.tar

      - name: Check images
        run: docker images

      - name: Start containers
        run: |
          if [[ "${{ matrix.abci }}" == "enabled" ]]; then
            docker-compose -f docker-compose.yml up -d planetmint
          fi
          if [[ ""${{ matrix.abci }}" == "disabled"" ]]; then
            docker-compose -f docker-compose.yml up -d bdb
          fi

      - name: Check running containers
        run: docker ps -a

      - name: Run tests
        run: |
          if [[ "${{ matrix.abci }}" == "enabled" ]]; then
            docker exec planetmint_planetmint_1 pytest -v -m abci
          fi
          if [[ ""${{ matrix.abci }}" == "disabled"" ]]; then
            docker exec planetmint_planetmint_1 pytest -v
          fi
