name: PyTest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build planetmint
        run: docker build . --file Dockerfile --tag planetmint:$(date +%s)

      # # - name: Store planetmint
      # - name: Build docker and start containers
      #   run: docker-compose -f ./planetmint/docker-compose.yml


  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - db: "MongoDB with ABCI"
            host: "mongodb"
            port: 27017
            abci: "enable"
          - db: "MongoDB without ABCI"
            host: "mongodb"
            port: 27017
            abci: "disable"
          - db: "Tarantool with ABCI"
            host: "tarantool"
            port: 3303
            abci: "enable"
          - db: "Tarantool without ABCI"
            host: "tarantool"
            port: 3303
            abci: "disable"

    steps:
      - name: Run tests
        run: |
          if [[ "${{ matrix.abci }}" == "enable" ]]; then
            docker-compose exec planetmint pytest -v -m abci
          fi
          if [[ "${{ matrix.abci }}" == "disable" ]]; then
            docker-compose exec planetmint pytest -v --cov=planetmint --cov-report xml:htmlcov/coverage.xml
          fi


      


